stream {
    map $ssl_preread_server_name $vusa_backend {
        www.google.com          vusa_reality_backend;
        vusa.bezrabotnyi.com    vusa_https_backend;
        default                 smart_edge_backend;
    }
    upstream vusa_reality_backend { server 127.0.0.1:23443; }
    upstream vusa_https_backend { server 127.0.0.1:8444; }
    upstream smart_edge_backend { server 127.0.0.1:9443; }
    server {
        listen 443;
        proxy_pass $vusa_backend;
        ssl_preread on;
        proxy_timeout 600s;
        proxy_connect_timeout 5s;
    }
}
